### ISSUE TITLE
Warning: Prop 'href' did not match. Server: "/" Client: "/about"

### ISSUE THREAD

**Issue by mparker11** [antonybudianto/cra-universal#38] opened 2018-03-20 21:31 UTC
Hi guys, hoping to get through this issue.

I have successfully achieved SSR with this package but one problem escapes me. Whenever I go directly to a url, say `/about`, I see this error: `Warning: Prop 'href' did not match. Server: "/" Client: "/about"`. Routing is fine and I can click through my app with no problem. It's only when going directly to a url in the address bar. The odd thing is, the content of the page shows but but inspector shows the code and css from the home page. 

Also, as expected, the client side is fine and renders everything correctly. I am using Curi router and my code for the server looks like this:
```
import { createReactAppExpress, handleUniversalRender } from '@cra-express/core';
import App from '../../src/containers/App';  
import Mixpanel from 'mixpanel';

const path = require('path');
const React = require('react');
const curi = require('@curi/core');
const InMemory = require('@hickory/in-memory');
const { CuriProvider } = require('@curi/react');

const { default: routes } = require('../../src/routes');
const memoryHistory = InMemory();
const router = curi(memoryHistory, routes);

const clientBuildPath = path.resolve(__dirname, 'client');
const app = createReactAppExpress({
    clientBuildPath,
    universalRender: handleUniversalRender(
        <CuriProvider router={ router }>
        {
            ({ response }) => {
                const { body: Body, data, params } = response;    
                return (
                    <App router={ router } response={ response }>
                        <Body data={ data } params={ params } />
                    </App>
                )
            }
        }
        </CuriProvider>
    )
});

module.exports = app;

```

Is there anything that jumps out that I may be doing wrong? Your help is much appreciated.

**Comment by mparker11** [comment] 2018-03-20 22:49
I've been combing through the package and I found a `universalLoader` function that has the line `app.use('/', universalMiddleware);`. Could this be the reason my app isn't grabbing data from the other routes? 

Just trying to understand the code. Thanks!

**Comment by antonybudianto** [comment] 2018-03-21 00:45
FYI https://github.com/antonybudianto/cra-universal/wiki/Getting-help

Sorry, I cannot help much with that snippet alone.

```
The odd thing is, the content of the page shows but but inspector shows the code and css from the home page.
```
What's the expectation? If you route from home using react-router, then it's expected to show the html code from home, since it's not hitting SSR server.

**Comment by mparker11** [comment] 2018-03-21 00:55
Thanks for your reply. The expectation is to be able to manually visit `localhost:3001/about` and have the correct markup/styles show. As of now, routing is fine and I can jump from page to page. 

However, I can only manually visit the homepage `/` and have it correctly show everything. Any other route and it shows the homepage's markup and shows the error `Warning: Prop 'href' did not match. Server: "/" Client: "/about"`

**Comment by antonybudianto** [comment] 2018-03-21 01:03
`correct markup/styles show.` means?

**Comment by mparker11** [comment] 2018-03-21 01:07
When I'm on the homepage for example, I see a div with a class `home-page` and the css associated with it. Unfortunately, when I go to the About page (/about), I still see `home-page` (and the same css) when I should see `about-page`. This only happens when I manually type in the url to /about.

**Comment by antonybudianto** [comment] 2018-03-21 01:09
`when I go to` means `manually type in the url` ? or visiting through router link ?

**Comment by antonybudianto** [comment] 2018-03-21 01:11
visiting manually should be no problem, just like https://cra-universal.now.sh/feature, but if you visit the feature link using react router link, then it's expected the html source is still the initial one (home)

**Comment by mparker11** [comment] 2018-03-21 01:13
Manually typing in the url. Thanks for the link. That makes sense. Have you ever seen the error before?
`Warning: Prop 'href' did not match. Server: "/" Client: "/about"`

It seems like not many people have run into it.

**Comment by antonybudianto** [comment] 2018-03-21 01:33
I never encountered that before.

**Comment by antonybudianto** [comment] 2018-03-21 08:28
Closing for now since it's not related to the CLI itself, I recommend using react-router for SSR

**Closed by antonybudianto** 2018-03-21 08:28 UTC

**Comment by abdessamadelhamdany** [comment] 2021-07-29 11:32
I think the issue is referencing a route that doesn't exist

example:
 `<Link href="#" passHref>...</Link>`

or in place of `#` any unexisting page

and you visit a route with queryString `?name=...` 

this was my case anyway

**Comment by alexandrepaiva-dev** [comment] 2022-02-18 23:13
I was having this issue too, the problem was that as @abdessamadelhamdany gave the example of:

`<Link href="#" passHref>...</Link>`

I had that hashtag on my <Link /> too, after removing them (for anything like just "/") the error message went away.
